name: Pistol Owners
favicon: null
layout_spectrum: 0.77325
typography_spectrum: 0.71015
title: Pistol Owners
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ada39a'
    - '#363640'
    - '#5e5d6d'
    - '#d8466a'
  brandStrength: 0.7964542887639254
  lightness: 0.12585266726091504
  saturation: 0.10050672525539994
  rhythmicContrast: 0.9483801268506795
purpose: []
